GET https://anticona23-fictional-space-orbit-9pg765r74grcxr9x-8080.preview.app.github.dev/

###
@server = https://anticona23-fictional-space-orbit-9pg765r74grcxr9x-8080.preview.app.github.dev

###
GET {{server}}

### CATEGORIAS ###

### Listando categoria
GET {{server}}/categorias

### Agregando categoria
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Instrumentos de percusión"}

### INSTRUMENTOS ###

### Listando instrumento
GET {{server}}/instrumentos

### Agregando instrumento
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Timbales", "categoria": "https://anticona23-fictional-space-orbit-9pg765r74grcxr9x-8080.preview.app.github.dev/categorias/3"}


###
GET {{server}}/categorias/3/instrumentos

###
GET {{server}}/instrumentos?sort=nombre,desc

### Probando Web Service Render
@server2 = https://ec3anticona.onrender.com

### Prueba 1
GET {{server2}}/categorias/3/instrumentos

### Prueba 2
GET {{server2}}/categorias

### Prueba 2
GET {{server2}}/instrumentos

